<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

/**
 * Class AdminGroup
 * @property int adgroup_id
 * @property string name
 * @property string description
 * @property string status
 * @property string admenu_ids
 * @package App\Models
 */
class AdminGroup extends BaseModel
{
    use HasFactory;

    protected $table = ADMIN_GROUP_TBL;
    protected $primaryKey = 'adgroup_id';

    const CREATED_AT = null;
    const UPDATED_AT = null;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'admenu_ids',
        'description',
        'status',
    ];


    /**
     * @return Builder
     */
    public static function query()
    {
        return parent::query()->whereNotIn('adgroup_id', ROOT_GROUP_IDS); // TODO: Change the autogenerated stub
    }
}
